---
config:
  flowchart:
    curve: basis
---
graph LR

%% Internal Python module dependencies
%% Standalone scripts use stadium shape ([...])
%% Library modules use default rectangle shape [...]

    subgraph common
        mod_common_common[common.common]
        mod_common_kepler[common.kepler]
        mod_common_oem[common.oem]
        mod_common_tle[common.tle]
        mod_common_omm[common.omm]
        mod_common_convert_tle[common.convert_tle]
    end

    subgraph frame_conversion
        mod_frame_conversion_gcrf_to_itrf_rot_model([gcrf_to_itrf_rot_model])
        mod_frame_conversion_gcrf_to_itrf_spice([gcrf_to_itrf_spice])
    end

    subgraph propagation
        mod_propagation_propagate_satellite_orbit([propagate_satellite_orbit])
        mod_propagation_propagate_tle([propagate_tle])
    end

    subgraph tle
        mod_tle_tle_info([tle_info])
        mod_tle_omm_to_tle([omm_to_tle])
        mod_tle_tle_to_omm([tle_to_omm])
        mod_tle_build_tle([build_tle])
        mod_tle_download_tle([download_tle])
    end

    subgraph test
        mod_test_test_common([test_common])
        mod_test_test_kepler([test_kepler])
        mod_test_test_oem([test_oem])
        mod_test_test_omm([test_omm])
        mod_test_test_tle([test_tle])
        mod_test_test_propagate_build_tle([test_propagate_build_tle])
        mod_test_test_convert_tle([test_convert_tle])
    end

    subgraph time_conversion
        mod_time_conversion_tools_convert_time([convert_time])
        mod_time_conversion_tools_convert_time2([convert_time2])
    end

    subgraph misc
        mod_misc_evaluate_build_tle_from_oem([evaluate_build_tle_from_oem])
        mod_misc_tudat_datetime_bug_60plus_seconds([tudat_datetime_bug_60plus_seconds])
        mod_misc_tudat_datetime_bug_incorrect_py_datetime([tudat_datetime_bug_incorrect_py_datetime])
        mod_misc_tudat_tdb_conversion_bug([tudat_tdb_conversion_bug])
    end

    %% Edges
    mod_common_convert_tle --> mod_common_common
    mod_common_convert_tle --> mod_common_tle
    mod_common_convert_tle --> mod_common_omm
    mod_common_kepler --> mod_common_tle
    mod_frame_conversion_gcrf_to_itrf_rot_model --> mod_common_common
    mod_frame_conversion_gcrf_to_itrf_spice --> mod_common_common
    mod_propagation_propagate_satellite_orbit --> mod_common_common
    mod_propagation_propagate_tle --> mod_common_common
    mod_test_test_convert_tle --> mod_common_convert_tle
    mod_test_test_convert_tle --> mod_common_omm
    mod_test_test_convert_tle --> mod_common_tle
    mod_test_test_kepler --> mod_common_kepler
    mod_test_test_kepler --> mod_common_tle
    mod_test_test_oem --> mod_common_oem
    mod_test_test_omm --> mod_common_omm
    mod_test_test_tle --> mod_common_tle
    mod_tle_build_tle --> mod_common_kepler
    mod_tle_build_tle --> mod_common_tle
    mod_tle_build_tle --> mod_common_oem
    mod_tle_omm_to_tle --> mod_common_convert_tle
    mod_tle_omm_to_tle --> mod_common_omm
    mod_tle_omm_to_tle --> mod_common_tle
    mod_tle_tle_info --> mod_common_common
    mod_tle_tle_to_omm --> mod_common_convert_tle
    mod_tle_tle_to_omm --> mod_common_tle
    mod_tle_tle_to_omm --> mod_common_omm
    mod_test_test_common --> mod_common_common
    mod_test_test_propagate_build_tle --> mod_common_tle
    mod_misc_evaluate_build_tle_from_oem --> mod_common_oem
    mod_misc_evaluate_build_tle_from_oem --> mod_common_common
